# Generated by Django 5.2.4 on 2026-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium lounge item'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('bar', 'Bar'), ('lounge', 'Lounge'), ('both', 'Both')], default='bar', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine'), ('spirit', 'Spirit'), ('soft_drink', 'Soft Drink'), ('juice', 'Juice'), ('cocktail', 'Cocktail'), ('food', 'Food'), ('cocktail', 'Cocktail'), ('wine', 'Wine'), ('champagne', 'Champagne'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('premium_spirit', 'Premium Spirit'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
